Hometask
==

**Do not change cells with markdown code**

You need to upload:
* this ipynb file 


**NB!:, Some tasks requires variables to be executed from the next cell. Do not modify this values anywhere except this cell - we will change this variables during the checking process.**

In [ ]:
Harry_Potter =  ["&A breeze ruffled the neat hedges of Privet Drive, ",
                "which lay silent and tidy under the inky sky,,, ", 
                 'HARRY',
                "%%%the very last place you would expect astonishing things to happen. ", 
                "Harry Potter rolled over inside his blankets without waking up."] 

Faust = [ "Ihr naht euch wieder,,, schwankende Gestalten, ", 
        "Die früh sich einst dem trüben Blick gezeigt. ", 
        "Versuch ich wohl,,, euch diesmal festzuhalten? ",
        "%%%Fühl ich mein Herz noch jenem Wahn geneigt????"]

Le_Petit_Prince  = ["Les hommes n'ont plus le temps de rien connaître. ", 
                    'DFKF',
                    "%%%%%%Il achètent des choses toutes faites chez les marchands. ",
                    "Mais comme il n'existe point de marchands d'amis, les hommes n'ontplus d'amis.. ",
                    "&Si tu veux un ami, apprivoise-moi!"] 

authors_and_works = {"Daniel Defoe" : {"Robinson Crusoe" : 1719, "A Journal of the Plague Year" : 1722},
                     "Johann Wolfgang von Goethe" : {"Faust" : 1832, "Egmont" : 1788, 'The Forest King' : 1782},
                     "Ernest Miller Hemingway" : {"The Old Man and the Sea" : 1952, "For Whom the Bell Tolls" : 1940},
                     "Joanne Rowling" : {"Harry Potter and the Philosopher's Stone" : 1997, 'The Cuckoo’s Calling' : 2013},
                     "Antoine de Saint-Exupery" : {'The Little Prince' : 1943, 'Land of men' : 1938}}
kdrama_info = {'Ojingeo geim': {'name': 'Игра в кальмара', 'genre': 'триллер, драма','age restrictions': 18, 'year': 2021, 'actors': ['Ли Джон-джэ', 'Пак Хэ-су', 'О Ён-су', 'Чон Хо-ён', 'Хо Сон-тхэ', 'Анупам Трипати', 'Ким Джу-рён', 'Ви Ха-джун', 'Ю Сон-джу', 'Ли Ю-ми'], 'rating': 7.5, 'review': 'Сон Ги-хун уже немолод, разведён, по уши погряз в долгах и сидит на шее у старенькой матери. Даже выигранные на скачках деньги в его руках долго не задерживаются, и однажды он встречает в метро загадочного незнакомца, который сначала предлагает сыграть в детскую игру, а затем вручает Ги-хуну немалую сумму и визитку. Но радость мужчины сменятся отчаянием, когда он узнаёт, что бывшая жена с новым мужем собираются увезти его дочь в Америку. Он звонит по номеру с визитки и становится последним участником тайных игр на выживание с призом в 40 миллионов долларов. Среди товарищей по несчастью оказываются его друг детства — прогоревший финансист, бандит, смертельно больной старик, северокорейская перебежчица, иммигрант из Пакистана и многие другие отчаянно нуждающиеся в деньгах.' },
        'Kimbiseoga wae geureolkka?': {'name': 'Что случилось с секретарём Ким?', 'genre': 'мелодрама', 'age restrictions': 12, 'year': 2018,'actors': ['Пак Со-джун', 'Пак Мин-ён', 'Хван Чхан-сон', 'Ли Тхэ-хван', 'Пхё Е-джин', 'Ким Хе-ок','Ким Бён-ок', 'Кан Ги-ён', 'Кан Хон-сок', 'Хван Бо-ра'], 'rating': 8.1, 'review': 'Богатый наследник Ли Ён-джун занимает должность вице-президента семейной компании. Он красив, умён и высокомерен. Его секретарь Ким Ми-со работала с ним несколько лет и идеально справлялась с работой, но теперь девушка решила уволиться.'},
        'Haepiniseu': {'name': 'Счастье', 'genre': 'фантастика, драма, ужасы, мелодрама', 'age restrictions': 16, 'year': 2021, 'actors': ['Хан Хё-джу', 'Пак Хён-щик', 'Чо У-джин', 'Ли Джун-хёк', 'Пэк Хён-джин', 'Пэ Хэ-сон', 'Мун Е-вон', 'Пак Хён-су', 'Чон Ун-сон', 'Сон Джи-у'], 'rating': 8.3, 'review': 'Люди разных социальных статусов из-за вируса застревают в элитной высотке. Фантастический триллер из Кореи'},
         'Saikojiman gwaenchanha': {'name': 'Я псих, но это нормально', 'genre': 'драма, мелодрама, фэнтези', 'age restrictions': 12, 'year': 2020, 'actors': ['Ким Су-хён', 'Со Е-джи', 'Пак Кю-ён', 'О Джон-сэ', 'Ким Джу-хон', 'Пак Чин-джу', 'Ким Чхан-ван', 'Чан Ён-нам', 'Кан Ги-дун', 'Ким Ми-гён'], 'rating': 8.2, 'review': 'История о сотруднике больницы для душевнобольных, который вынужден ухаживать за особенным братом, и популярной детской писательнице с диссоциальным расстройством личности.'}}


li_fruits = ["pea$r", 12, "orange", "pe?!ar", "45", 31, "o1range", "pea!r", "a1ppl.e", "orange", "peach?", "li5me", 25.6, "pear0", "pear", ".", " pe ach "]
heroes = {"Yui Kodai":["5$", 30, 25, 38, 31],
         "Izuku Midoriya":["15$", 45, 40, 50, 42], 
         "Momo Yaoyorozu":["20$", 44, 42, 46, 39], 
         "Toshinori Yagi":["35$", 60, 59, 57, 63], 
         "Katsuki Bakugo":["30$", 50, 52, 54, 56], 
         "Tenya Ida":["20$", 60, 62, 64, 60], 
         "Anan Kurose":["30$", 40, 45, 42, 38], 
         "Tetsutetsu Tetsutetsu":["10$", 55, 55, 51, 45], 
         "Shoto Todoroki":["25$", 48, 50, 47, 52], 
         "Eijiro Kirishima":["15$", 42, 40, 45, 45], 
         "Yuga Aoyama":["15$", 25, 28, 20, 22], 
         "Shota Aizawa":["28$", 50, 51, 49, 50], 
         "Hizashi Yamada":["35$", 29, 28, 30, 31], 
         "Tsuyu Asui":["20$", 45, 44, 48, 46],
         "Mashirao Ojiro":["17$", 32, 35, 38, 40],
         "Ochaco Uraraka":["19$", 39, 35, 37, 40],
         "Denki Kaminari":["15$", 30, 28, 25, 35],
         "Fumikage Tokoyami":["20$", 34, 40, 40, 45],
         "Mina Ashido":["21$", 35, 35, 32, 36],
         "Emi Fukukado":["30$", 55, 56, 50, 55]}
staff = [' Aizawa ', ' Fukukado', 'Kur+ose', 'Yagi_', 'Yam ada']
intern = ['Aoyama ', 'Ashido0', 'As?ui', 'Ba!kugo', 'Ida5', 'Kam_inari', 'Kirishima', 'Kod_ai', 'Midoriya1', 'Ojiro', 'Tetsutetsu', 'Todoroki%', 'Tokoyami', 'Ur@araka', 'Yao3yorozu']
minimum_hours = (180, 125)
stream = "1gsGdhhThji1trjn1Mjty1tyjyt1r0j1jhfRdfrthEdg0jut0rtrWyh1hgtyXj1jhgfgYhgyu0tyhjfhgdf"
notation = {'8':{'000':'0','001':'1','010':'2','011':'3','100':'4','101':'5','110':'6','111':'7'},
            '16':{'0000':'0','0001':'1','0010':'2','0011':'3','0100':'4','0101':'5','0110':'6','0111':'7','1000':'8','1001':'9','1010':'A','1011':'B','1100':'C','1101':'D','1110':'E','1111':'F'}
}

## Task 1

**1.1)** You are given 3 texts in different languages, stored in the variables **Harry_Potter**, **Faust**, **Le_Petit_Prince** in the format of list with strings. Clear the elements of each list from extra characters. Extra characters are: 
- a **sequence** of identical punctuation characters (in case of finding such in the text, you should delete all the characters of this sequence, except one). Possible punctuation marks: ".", ",", "!", "?" (for example, 'sky,,,' -> 'sky,' )
- strings that contain **only** uppercase letters (for example, 'HELLO' -> need to be removed, 'HELLO!' -> do not need to be removed)
- **"%" or "&"** at the **beginning** of all strings where they occur ('%%%%%%Il achètent' -> 'Il achètent')

Turn each list of strings into a single string. Write the resulting single corrected text into the variables **Harry_Potter_1** (type:str), **Faust_1** (type:str), **Le_Petit_Prince_1** (type:str), respectively.

**Example**:
~~~
for_example = ['HARRY',
                '&Mr and Mrs Dursley, of number four, Privet Drive,,, &',
                '%%%were proud to say that they were perfectly no%rmal, thank you very much!!! ']
for_example_1 = 'Mr and Mrs Dursley, of number four, Privet Drive, &were proud to say that they were perfectly no%rmal, thank you very much! '
~~~

**Remember** that we will change the content of the variables **Harry_Potter**, **Faust**, **Le_Petit_Prince** while checking your solution!

**1.2)** Using the data in the **authors_and_works** variable, determine the author who has the largest interval between the first and last released work (presented in the dictionary). Write down the full name of the author into the string variable **author** (type:str). 

The structure of the **authors_and_works** dictionary:
~~~
{"author's name" : {"work's title" : publication year, "work's title" : publication year}}, etc.
~~~

**Example:**

~~~
authors_and_works = {'Author One': {'book 1': 1987},
              'Author Two': {'book 1': 1232, 'book 2': 1432, 'book 3': 1267, 'book 4': 1643},
              'Author Three': {'book 1': 1234, 'book 2': 2005, 'book 3': 1567}}
author = 'Author Three'
because 
'Author One' -> 1987 - 1987 = 0
'Author Two' -> 1643 - 1232 = 411
'Author Three' -> 2005 - 1234 = 771  # the largest
~~~

**Remember** that we will change the content of the dictionary **authors_and_works** while checking your solution!  

Variables that will be checked: **Harry_Potter_1, Faust_1, Le_Petit_Prince_1, author**

In [ ]:
# Harry_Potter_1
# Faust_1
# Le_Petit_Prince_1
# author

## Task 2


You have a nested dictionary **kdrama_info**, which contains information about popular Korean TV series. The keys in this dictionary are the titles of the series in Korean ([RR](https://en.wikipedia.org/wiki/Revised_Romanization_of_Korean)). The values are other dictionaries with the following keys:
- name - series’ name in Russian
- genre - TV series’ genre
- age restrictions - the youngest age at which you are allowed to watch this series
- year - the year of the series’ release
- actors - the list of actors
- rating - the series’ rating on Kinopoisk
- review - series’ description

**Remember** that we will change the content of the dictionary **kdrama_info** while checking your solution!

Your task is to write a function **get_info** that accepts as input:
* nested dictionary **kdrama_info**
* **at least** 1 (one) age value
* information about the series that you need to get (use named parameter **info**: set the **default value** to **"name; genre"**; the parameter value is a string where the information is separated by semicolon, for example, info='genre; year; rating')

The function should return:
* **pandas DataFrame** containing information about TV series that are suitable for all ages specified by a user at once (сериалы, которые подойдут для всех возрастов, переданных в функцию)

Take into account: 
- The first column of the table should **always** be the **age restrictions**(the content of the key **age restrictions**). The second column - the title of the series in Russian (the content of the key **name**). The remaining columns are the requested information.
- The column names must match the dictionary keys.
- If the user asks for the information about the series’ Korean title (пользователь передаст в параметр info значение "korean name"), then name the column as "**korean name**"
- If there are no series in the dictionary that satisfy the request, the function should return the phrase 'Для Вас нет подходящего сериала'
- There should be no duplicate columns in the table (например, если пользователь передал в параметр info значение name, то Ваша функция должна справиться с этим и не добавлять в таблицу второй столбец name)
- **Sort the dataframe by the "name" column in ascending order** (это важно)
- **Reset the indexes**

**Example:**

~~~
get_info(kdrama_info, 5, 4, 6, 7)
~~~
'Для Вас нет подходящего сериала'

~~~
get_info(kdrama_info, 18, 16, 16, 18)
~~~

|    |   age restrictions | name                            | genre                               |
|---:|-------------------:|:--------------------------------|:------------------------------------|
|  0 |                 16 | Счастье                         | фантастика, драма, ужасы, мелодрама |
|  1 |                 12 | Что случилось с секретарём Ким? | мелодрама                           |
|  2 |                 12 | Я псих, но это нормально        | драма, мелодрама, фэнтези           |

~~~
get_info(kdrama_info, 35, 45, 37, info='korean name; genre; rating; age restrictions')
~~~

|    |   age restrictions | name                            | korean name                | genre                               |   rating |
|---:|-------------------:|:--------------------------------|:---------------------------|:------------------------------------|---------:|
|  0 |                 18 | Игра в кальмара                 | Ojingeo geim               | триллер, драма                      |      7.5 |
|  1 |                 16 | Счастье                         | Haepiniseu                 | фантастика, драма, ужасы, мелодрама |      8.3 |
|  2 |                 12 | Что случилось с секретарём Ким? | Kimbiseoga wae geureolkka? | мелодрама                           |      8.1 |
|  3 |                 12 | Я псих, но это нормально        | Saikojiman gwaenchanha     | драма, мелодрама, фэнтези           |      8.2 |

Column Types:

|| |
|---:|:-------------------------|
|name    |             object|
|genre    |            object|
|age restrictions   |   int64|
|year         |         int64|
|actors       |        object|
|rating       |       float64|
|review       |        object|

In [ ]:
# def get_info():

## Task 3

In the list **li_fruits** there is information about fruits purchases. However, there were some data recording problems and now some elements in the list **li_fruits** contain extra symbols (numbers, punctuation marks, etc.) that should be removed ("!a1p.pl2e" => "apple"). Also there are some other elements that contain ONLY numbers and punctution marks (for example, "47", "12?3.5", 35, or 3.5) that should be deleted from the list.

Create a dictionary **fruits_describe** and define its elements:
1. The key is **fruits**, its value is a dictionary where keys are cleaned elements from list **li_fruits** and values are the number of times the corresponding element appears in the list **li_fruits** (type int)
2. The key is **max**, its value is the maximum value in the dictionary from the first step (type int)
3. The key is **min**, its value is the minimum value in the dictionary from the first step (type int)
4. The key is **sum**, its value is the sum of all values in the dictionary from the first step (type int)


*Example:*

**li_fruits** = ["orange", "ora46ng.!e", "1234.5", "a1p90ple", "orange", "!", 10057]  
        
*Result:*

**fruits_describe** = 

                  {"fruits":{"orange": 3, "apple": 1}, 
                   "max": 3, 
                   "min": 1, 
                   "sum": 4}

In [ ]:
# fruits_describe =

## Task 4

In the dictionary **heroes** there are data about hourly wage of each hero (first element in the list) and number of hours worked in each of 4 past weeks (2nd-5th elements). Some of the heroes are employees in an agency and some of them are interns. You can see their surnames in lists **staff** and **intern** respectively. 

The agency decided to increase the hourly wage of employees by **35%** and hourly wage of interns by **15%**. But heroes have to meet the standard of hours worked in a month. The minimum number of hours worked in a month for employees and interns are mentioned in the tuple **minimum_hours** as first and second element respectively. 

Create a dictionary **wages** with names of heroes as keys. Put lists with two elements as values: 
1. The value of hourly wage after increase in the form **"00\$"** rounded to the whole number IN CASE THE HOURS WORKED STANDARD IS MET. Otherwise, DO NOT recalculate the hourly wage and put string **"standard not met, \[current hourly wage value\]"** as a first element of the list,
2. The value of wage for the whole month in the form  **"00\$"** using NEW value of hourly wage (after recalculation). Hourly wage should be rounded to the whole number.

Please pay attention that surnames in lists **staff** and **intern** may contain any extra symbols (numbers, punctuation marks, etc.) that should be deleted.

Remember that the values of ALL variables (including the names and the number of heroes) might be changed by us during checking of your work.

**Example**

<code>
heroes = {"Yui Kodai":["4$", 1, 2, 3, 4],
         "Izuku Midoriya":["7$", 1, 1, 1, 2], 
         "Anan Kurose":["10$", 4, 5, 6, 8],
         "Emi Fukukado":["11$", 5, 1, 2, 3]}
staff = [' Fukukado', 'Kur+ose']
intern = ['Kod_ai', 'Midoriya1']
minimum_hours = (12, 9)
</code>

**Result**

<code>
wages = {"Yui Kodai":["5$", "50$"],
         "Izuku Midoriya":["standard not met, 7$", "35$"], 
         "Anan Kurose":["14$", "322$"],
         "Emi Fukukado":["standard not met, 11$", "121$"]}
</code>

In [ ]:
#wages = ...

## Task 5

You are given a variable called **stream**, containing a certain set of symbols, and a variable called **notation**, containing match-lists for conversion into octal and hexadecimal.    

Delete excess symbols from **stream** to get a binary code, assign it to a variable called **binary**.           
You should also count all capital letters in **stream**. The resulting number is the notation to which you will convert your code from the **binary** variable. Assign the result to **binary_transformed** *as a string format*.

Note:
- there can only be octal, decimal or hexadecimal
- [converting binary into decimal](https://www.cuemath.com/numbers/binary-number-system/)
- conversion into 8 and 16 is done by splitting and substitution of binary code (see **notation**)

**Example:**
~~~
stream = 'AAAfb1dd378VG0ncd%HVuj&S1YT' (10 capital letters)
binary = '101'
binary_transformed = '5'
~~~
**Remember** that the content of given variables will be changed during the checking!  

Variables that will be checked: **binary, binary_transformed**

In [ ]:
# binary = ...
# binary_transformed = ...

## Task 6

Read these two datasets using pandas: \
https://raw.githubusercontent.com/ksegorov/python_homework/main/var1/df.csv \
https://raw.githubusercontent.com/ksegorov/python_homework/f256dcce337f82e9d25e867c31c217016832d9fc/var1/grades.csv 

Combine the specified datasets using unique student IDs so that the columns from dataset **df** are on the right side, and load the result into a new variable **df_new**.

Filter the dataframe so that it does not contain Na or "-" values. Save the result to the same variable.

Filter the merged dataset so that only those students who have a value of 'Yes' in the **is_Commercial** column remain. Load the dataframe into the **df_new** variable.

If the variables to be numeric are of type string, change this type to numeric(or int64 type).

Sort **df_new** by the **Student_ID** column in descending order.  Save the changes.

In the variable **value**, using the filtered dataset, calculate and load the minimum grade for those students. Data type of the variable **value** should be **int**.


*Hint: You can either hardcode your solution or use ready-made Pandas library functions and methods. Use the cheatsheet!
p.s. 
the process of formatting dataframes will also be checked :)*

In [4]:
import pandas as pd
# df = 
# df_new = 
# value =